add a fail check to battery-checker

diff --git a/.local/bin/battery_checker b/.local/bin/battery_checker
--- a/.local/bin/battery_checker
+++ b/.local/bin/battery_checker
@@ -7,6 +7,11 @@ else
   BAT=$1 # allow to pass an argument for easier debugging
 fi
 
+if ! [[ $BAT =~ ^[0-9]+$ ]]; then
+  dunstify -h string:x-dunst-stack-tag:battery-error  "Failed to query battery info" "acpi -b output:\n$(acpi -b)"
+  exit 1
+fi
+
 STATE_FILE="/home/kobu/.local/state"
 # Sets severity of battery level:
   # critical -> 0
@@ -20,7 +25,7 @@ elif [ $BAT -le 15 ]; then
   CURRENT=1
 elif [ $BAT -le 50 ]; then
   CURRENT=2
-elif [ $BAT -eq 100 ]; then
+elif [ $BAT -ge 99 ]; then
   CURRENT=3
 else
   CURRENT=4 # this will never cause a notification
